package banco.ui;

public class TelaMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName());

    private String nomeUsuario;
    private String perfilUsuario;
    
    public TelaMenuPrincipal(String nome, String perfil) {
        this.nomeUsuario = nome;
        this.perfilUsuario = perfil;
        
        initComponents();
        
        configurarTela();
    }
    
    private void configurarTela(){
        lbl_title.setText("Bem-vindo, " + nomeUsuario);
        
        if(perfilUsuario.equalsIgnoreCase("OPERADOR")){
            btn_gerenciar_usuarios.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lbl_title = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_cad_cliente = new javax.swing.JButton();
        btn_deposito = new javax.swing.JButton();
        btn_cad_corrente = new javax.swing.JButton();
        btn_saque = new javax.swing.JButton();
        btn_cad_poupanca = new javax.swing.JButton();
        btn_transferencia = new javax.swing.JButton();
        btn_relatorio = new javax.swing.JButton();
        btn_extrato = new javax.swing.JButton();
        btn_gerenciar_usuarios = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_title.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("teste");

        btn_logout.setText("Sair");
        btn_logout.addActionListener(this::btn_logoutActionPerformed);

        btn_cad_cliente.setText("Cadastrar Cliente");

        btn_deposito.setText("Depósito");
        btn_deposito.addActionListener(this::btn_depositoActionPerformed);

        btn_cad_corrente.setText("Cadastrar Conta Corrente");
        btn_cad_corrente.addActionListener(this::btn_cad_correnteActionPerformed);

        btn_saque.setText("Saque");

        btn_cad_poupanca.setText("Cadastrar Conta Poupança");

        btn_transferencia.setText("Transferência");

        btn_relatorio.setText("Relatório Geral");

        btn_extrato.setText("Extrato");

        btn_gerenciar_usuarios.setText("Gerenciar Usuários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_gerenciar_usuarios)
                        .addGap(134, 134, 134)
                        .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_logout))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_cad_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_cad_corrente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(433, 433, 433)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_deposito, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(btn_saque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_cad_poupanca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(433, 433, 433)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_transferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(btn_extrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_logout)
                    .addComponent(btn_gerenciar_usuarios)
                    .addComponent(lbl_title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cad_cliente)
                    .addComponent(btn_deposito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_cad_corrente)
                    .addComponent(btn_saque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cad_poupanca)
                    .addComponent(btn_transferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_relatorio)
                    .addComponent(btn_extrato))
                .addGap(166, 166, 166))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_cad_correnteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cad_correnteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cad_correnteActionPerformed

    private void btn_depositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_depositoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_depositoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cad_cliente;
    private javax.swing.JButton btn_cad_corrente;
    private javax.swing.JButton btn_cad_poupanca;
    private javax.swing.JButton btn_deposito;
    private javax.swing.JButton btn_extrato;
    private javax.swing.JButton btn_gerenciar_usuarios;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_relatorio;
    private javax.swing.JButton btn_saque;
    private javax.swing.JButton btn_transferencia;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbl_title;
    // End of variables declaration//GEN-END:variables
}
