/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.ui;

import banco.dao.ContaCorrenteDAO;
import banco.dao.ContaPoupancaDAO;
import banco.model.ContaBancaria;
import banco.model.ContaCorrente;
import banco.service.BancoService;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dutrax
 */
public class TelaExtrato extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaExtrato.class.getName());
    private DefaultTableModel tabelaModelo;
    /**
     * Creates new form TelaExtrato
     */
    public TelaExtrato() {
        initComponents();
        
        this.tabelaModelo = (DefaultTableModel) tbl_extrato.getModel();
        
        this.tabelaModelo.setColumnIdentifiers(new Object[]{ "Histórico de Movimentações" });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_numeroConta = new javax.swing.JLabel();
        edt_numeroConta = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_extrato = new javax.swing.JTable();
        lbl_warnings = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_title.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Extrato");

        lbl_numeroConta.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        lbl_numeroConta.setText("Número da conta:");

        edt_numeroConta.addActionListener(this::edt_numeroContaActionPerformed);

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(this::btn_buscarActionPerformed);

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(this::btn_voltarActionPerformed);

        tbl_extrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Operação", "Valor", "Hora"
            }
        ));
        jScrollPane1.setViewportView(tbl_extrato);

        lbl_warnings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_numeroConta)
                                .addGap(50, 50, 50)
                                .addComponent(edt_numeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 136, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_warnings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_buscar)
                .addGap(67, 67, 67)
                .addComponent(btn_voltar)
                .addGap(258, 258, 258))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_numeroConta)
                    .addComponent(edt_numeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_voltar))
                .addGap(33, 33, 33)
                .addComponent(lbl_warnings)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edt_numeroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_numeroContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_numeroContaActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        String conta = edt_numeroConta.getText().trim();
        
        if(conta.isEmpty()){
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Por favor, digite o número da conta!");
            return;
        }
        tabelaModelo.setNumRows(0);
        
        BancoService servico = new BancoService();
        ContaCorrenteDAO correnteDAO = new ContaCorrenteDAO();
        ContaPoupancaDAO poupancaDAO = new ContaPoupancaDAO();
        
        ContaBancaria cb = servico.buscarConta(conta);
        
        if(cb == null){
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Erro: Conta não localizada no sistema.");
            return;
        }
        
        int contaId = (int) cb.getId();
        List<String> historico;
        
        if(cb instanceof ContaCorrente){
            historico = correnteDAO.buscarHistorico(contaId);
        } else {
            historico = poupancaDAO.buscarHistorico(contaId);
        }
        
        if (historico == null || historico.isEmpty()) {
            lbl_warnings.setForeground(java.awt.Color.BLUE);
            lbl_warnings.setText("Nenhuma movimentação registrada para esta conta.");
            return;
        }

        for (String linhaTransacao : historico) {
            tabelaModelo.addRow(new Object[]{ linhaTransacao });
        }
        
        lbl_warnings.setForeground(new java.awt.Color(0, 150, 0));
        lbl_warnings.setText("Extrato updated com sucesso!");
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JTextField edt_numeroConta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_numeroConta;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_warnings;
    private javax.swing.JTable tbl_extrato;
    // End of variables declaration//GEN-END:variables
}
