/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.ui;

import banco.dao.ClienteDAO;
import banco.dao.ContaCorrenteDAO;
import banco.model.Cliente;
import banco.model.ContaCorrente;

/**
 *
 * @author dutrax
 */
public class TelaCadastroContaCorrente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroContaCorrente.class.getName());

    /**
     * Creates new form TelaCadastroContaCorrente
     */
    public TelaCadastroContaCorrente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_numeroConta = new javax.swing.JLabel();
        lbl_saldoInicial = new javax.swing.JLabel();
        lbl_limite = new javax.swing.JLabel();
        lbl_cpfTitular = new javax.swing.JLabel();
        edt_numeroConta = new javax.swing.JTextField();
        edt_saldoInicial = new javax.swing.JTextField();
        edt_limite = new javax.swing.JTextField();
        edt_cpfTitular = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        lbl_warnings = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_title.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Cadastrar Conta Corrente");

        lbl_numeroConta.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        lbl_numeroConta.setText("Número da conta:");

        lbl_saldoInicial.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        lbl_saldoInicial.setText("Saldo inicial:");

        lbl_limite.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        lbl_limite.setText("Limite:");

        lbl_cpfTitular.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        lbl_cpfTitular.setText("CPF do titular:");

        edt_cpfTitular.addActionListener(this::edt_cpfTitularActionPerformed);

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(this::btn_salvarActionPerformed);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(this::btn_cancelarActionPerformed);

        lbl_warnings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(btn_salvar)
                                .addGap(57, 57, 57)
                                .addComponent(btn_cancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_limite)
                                    .addComponent(lbl_saldoInicial)
                                    .addComponent(lbl_numeroConta)
                                    .addComponent(lbl_cpfTitular))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edt_numeroConta)
                                    .addComponent(edt_saldoInicial)
                                    .addComponent(edt_limite)
                                    .addComponent(edt_cpfTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 83, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_warnings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_title)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_numeroConta)
                    .addComponent(edt_numeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_saldoInicial)
                    .addComponent(edt_saldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_limite)
                    .addComponent(edt_limite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cpfTitular)
                    .addComponent(edt_cpfTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar)
                    .addComponent(btn_cancelar))
                .addGap(18, 18, 18)
                .addComponent(lbl_warnings)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edt_cpfTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_cpfTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_cpfTitularActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        String numero = edt_numeroConta.getText().trim();
        String saldoStr = edt_saldoInicial.getText().trim();
        String limiteStr = edt_limite.getText().trim();
        String cpf = edt_cpfTitular.getText().trim();
        
        if (numero.isEmpty() || saldoStr.isEmpty() || limiteStr.isEmpty() || cpf.isEmpty()) {
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Por favor, preencha todos os campos!");
            return;
        }
        
        double saldo, limite;
        try {
            saldo = Double.parseDouble(saldoStr);
            limite = Double.parseDouble(limiteStr);
        } catch (NumberFormatException e) {
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Saldo e Limite devem ser números válidos!");
            return;
        }
        
        ClienteDAO clienteDAO = new ClienteDAO();
        ContaCorrenteDAO correnteDAO = new ContaCorrenteDAO();
        
        Cliente titular = clienteDAO.buscarPorCpf(cpf);
        
        if(titular == null){
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Erro: Nenhum cliente localizado com o CPF informado.");
            return;
        }
        
        if(correnteDAO.buscaPorNumero(numero) != null){
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Erro: Já existe uma conta corrente com este número.");
            return;
        }
        
        ContaCorrente novaConta = new ContaCorrente(numero, titular, saldo, limite);
        
        boolean sucesso = correnteDAO.salvar(novaConta, titular.getId());
        
        if (sucesso) {
            lbl_warnings.setForeground(new java.awt.Color(0, 150, 0));
            lbl_warnings.setText("Conta Corrente aberta com sucesso!");
            
            edt_numeroConta.setText("");
            edt_saldoInicial.setText("");
            edt_limite.setText("");
            edt_cpfTitular.setText("");
            edt_numeroConta.requestFocus();
        } else {
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Erro físico ao salvar a conta corrente no banco.");
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroContaCorrente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JTextField edt_cpfTitular;
    private javax.swing.JTextField edt_limite;
    private javax.swing.JTextField edt_numeroConta;
    private javax.swing.JTextField edt_saldoInicial;
    private javax.swing.JLabel lbl_cpfTitular;
    private javax.swing.JLabel lbl_limite;
    private javax.swing.JLabel lbl_numeroConta;
    private javax.swing.JLabel lbl_saldoInicial;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_warnings;
    // End of variables declaration//GEN-END:variables
}
