/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.ui;

/**
 *
 * @author dutrax
 */
public class TelaOperacoes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaOperacoes.class.getName());
    private String operacaoDefinida;

    /**
     * Creates new form TelaOperacoes
     */
    public TelaOperacoes(String operacao) {
        this.operacaoDefinida = operacao;
        initComponents();
        configurarTelaDinamica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_numeroConta = new javax.swing.JLabel();
        lbl_valor = new javax.swing.JLabel();
        edt_numeroConta = new javax.swing.JTextField();
        edt_valor = new javax.swing.JTextField();
        lbl_conta_destino = new javax.swing.JLabel();
        edt_conta_destino = new javax.swing.JTextField();
        btn_confirmar = new javax.swing.JButton();
        lbl_warnings = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_title.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Operações");

        lbl_numeroConta.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        lbl_numeroConta.setText("Número da conta:");

        lbl_valor.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        lbl_valor.setText("Valor:");

        edt_numeroConta.setMinimumSize(new java.awt.Dimension(100, 30));
        edt_numeroConta.setName(""); // NOI18N

        edt_valor.setMinimumSize(new java.awt.Dimension(100, 30));

        lbl_conta_destino.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        lbl_conta_destino.setText("Conta destino:");

        edt_conta_destino.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        edt_conta_destino.setMinimumSize(new java.awt.Dimension(100, 30));

        btn_confirmar.setText("Confirmar");
        btn_confirmar.addActionListener(this::btn_confirmarActionPerformed);

        lbl_warnings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(this::btn_cancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_numeroConta)
                            .addComponent(lbl_valor)
                            .addComponent(lbl_conta_destino))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edt_numeroConta, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(edt_valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edt_conta_destino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_warnings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 205, Short.MAX_VALUE)
                .addComponent(btn_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_title)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_numeroConta)
                    .addComponent(edt_numeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_valor)
                    .addComponent(edt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_conta_destino)
                    .addComponent(edt_conta_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lbl_warnings, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmarActionPerformed
        String conta = edt_numeroConta.getText().trim();
        String valorStr = edt_valor.getText().trim();

        if (conta.isEmpty() || valorStr.isEmpty()) {
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Por favor, preencha todos os campos obrigatórios!");
            return;
        }
        
        double valor;
        try {
            valor = Double.parseDouble(valorStr);
        } catch (NumberFormatException e) {
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("O valor digitado deve ser um número válido!");
            return;
        }

        banco.service.BancoService servico = new banco.service.BancoService();
        String mensagemResultado = "";

        if (this.operacaoDefinida.equals("SAQUE")) {
            banco.model.ContaBancaria cb = servico.buscarConta(conta);
            if (cb instanceof banco.model.ContaCorrente) {
                mensagemResultado = servico.sacarCorrente(conta, valor);
            } else {
                mensagemResultado = servico.sacarPoupanca(conta, valor);
            }
            
        } else if (this.operacaoDefinida.equals("DEPOSITO")) {
            banco.model.ContaBancaria cb = servico.buscarConta(conta);
            if (cb instanceof banco.model.ContaCorrente) {
                mensagemResultado = servico.depositarCorrente(conta, valor);
            } else {
                mensagemResultado = servico.depositarPoupanca(conta, valor);
            }
            
        } else if (this.operacaoDefinida.equals("TRANSFERENCIA")) {
            String contaDestino = edt_conta_destino.getText().trim();
            if (contaDestino.isEmpty()) {
                lbl_warnings.setForeground(java.awt.Color.RED);
                lbl_warnings.setText("Informe a conta de destino para a transferência!");
                return;
            }
            mensagemResultado = servico.transferir(conta, contaDestino, valor);
        }
        
        if (mensagemResultado.startsWith("Sucesso")) {
            lbl_warnings.setForeground(new java.awt.Color(0, 150, 0)); 
            edt_valor.setText(""); 
        } else {
            lbl_warnings.setForeground(java.awt.Color.RED);
        }
        
        lbl_warnings.setText(mensagemResultado);
    }//GEN-LAST:event_btn_confirmarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed
    
    private void configurarTelaDinamica(){
        if (this.operacaoDefinida.equals("SAQUE")) {
            lbl_title.setText("Operação: Saque Bancário");
            btn_confirmar.setText("Confirmar Saque");
            lbl_conta_destino.setVisible(false);
            edt_conta_destino.setVisible(false);
        } 

        else if (this.operacaoDefinida.equals("DEPOSITO")) {
            lbl_title.setText("Operação: Depósito Bancário");
            btn_confirmar.setText("Confirmar Depósito");
            lbl_conta_destino.setVisible(false);
            edt_conta_destino.setVisible(false);
        }

        else if (this.operacaoDefinida.equals("TRANSFERENCIA")) {
            lbl_title.setText("Operação: Transferência (TED/Pix)");
            btn_confirmar.setText("Confirmar Transferência");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JTextField edt_conta_destino;
    private javax.swing.JTextField edt_numeroConta;
    private javax.swing.JTextField edt_valor;
    private javax.swing.JLabel lbl_conta_destino;
    private javax.swing.JLabel lbl_numeroConta;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_valor;
    private javax.swing.JLabel lbl_warnings;
    // End of variables declaration//GEN-END:variables
}
