/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.ui;

/**
 *
 * @author dutrax
 */
public class TelaCadastroContaPoupanca extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroContaPoupanca.class.getName());

    /**
     * Creates new form TelaCadastroContaPoupanca
     */
    public TelaCadastroContaPoupanca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_numeroConta = new javax.swing.JLabel();
        lbl_saldoInicial = new javax.swing.JLabel();
        lbl_cpfTitular = new javax.swing.JLabel();
        edt_numeroConta = new javax.swing.JTextField();
        edt_saldoInicial = new javax.swing.JTextField();
        edt_cpfTitular = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        lbl_warnings = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_title.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Cadastrar Conta Poupança");

        lbl_numeroConta.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        lbl_numeroConta.setText("Número da Conta:");

        lbl_saldoInicial.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        lbl_saldoInicial.setText("Saldo inicial:");

        lbl_cpfTitular.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        lbl_cpfTitular.setText("CPF do titular:");

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(this::btn_salvarActionPerformed);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(this::btn_cancelarActionPerformed);

        lbl_warnings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_numeroConta)
                                    .addComponent(lbl_saldoInicial)
                                    .addComponent(lbl_cpfTitular))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edt_numeroConta)
                                    .addComponent(edt_saldoInicial)
                                    .addComponent(edt_cpfTitular, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(btn_salvar)
                                .addGap(57, 57, 57)
                                .addComponent(btn_cancelar)))
                        .addGap(0, 73, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_warnings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_title)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_numeroConta)
                    .addComponent(edt_numeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_saldoInicial)
                    .addComponent(edt_saldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cpfTitular)
                    .addComponent(edt_cpfTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar)
                    .addComponent(btn_cancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lbl_warnings)
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        String numero = edt_numeroConta.getText().trim();
        String saldoStr = edt_saldoInicial.getText().trim();
        String cpf = edt_cpfTitular.getText().trim();
        
        if (numero.isEmpty() || saldoStr.isEmpty() || cpf.isEmpty()) {
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Por favor, preencha todos os campos!");
            return;
        }

        double saldo;
        try {
            saldo = Double.parseDouble(saldoStr);
        } catch (NumberFormatException e) {
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("O saldo inicial deve ser um número válido!");
            return;
        }

        banco.dao.ClienteDAO clienteDAO = new banco.dao.ClienteDAO();
        banco.dao.ContaPoupancaDAO poupancaDAO = new banco.dao.ContaPoupancaDAO();

        banco.model.Cliente titular = clienteDAO.buscarPorCpf(cpf);
        if (titular == null) {
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Erro: Nenhum cliente localizado com o CPF informado.");
            return;
        }

        if (poupancaDAO.buscarPorNumero(numero) != null) {
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Erro: Já existe uma conta poupança com este número.");
            return;
        }
        
        double taxa = 0.005;
        banco.model.ContaPoupanca novaPoupanca = new banco.model.ContaPoupanca(numero, titular, saldo, taxa);
        
        boolean sucesso = poupancaDAO.salvar(novaPoupanca, titular.getId());
        
        if (sucesso) {
            lbl_warnings.setForeground(new java.awt.Color(0, 150, 0)); // Verde
            lbl_warnings.setText("Conta Poupança aberta com sucesso!");

            edt_numeroConta.setText("");
            edt_saldoInicial.setText("");
            edt_cpfTitular.setText("");
            edt_numeroConta.requestFocus();
        } else {
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Erro físico ao salvar a conta poupança no banco.");
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JTextField edt_cpfTitular;
    private javax.swing.JTextField edt_numeroConta;
    private javax.swing.JTextField edt_saldoInicial;
    private javax.swing.JLabel lbl_cpfTitular;
    private javax.swing.JLabel lbl_numeroConta;
    private javax.swing.JLabel lbl_saldoInicial;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_warnings;
    // End of variables declaration//GEN-END:variables
}
