/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.ui;

import banco.dao.ClienteDAO;
import banco.model.Cliente;

/**
 *
 * @author dutrax
 */
public class TelaCadastroCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName());

    /**
     * Creates new form TelaCadastroCliente
     */
    public TelaCadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        lbl_cpf = new javax.swing.JLabel();
        edt_cpf = new javax.swing.JTextField();
        edt_nome = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        lbl_warnings = new javax.swing.JLabel();
        lbl_telefone = new javax.swing.JLabel();
        edt_telefone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_title.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Cadastrar Novo Cliente");

        lbl_nome.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        lbl_nome.setText("Nome:");

        lbl_cpf.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        lbl_cpf.setText("CPF:");

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(this::btn_salvarActionPerformed);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(this::btn_cancelarActionPerformed);

        lbl_warnings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbl_telefone.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        lbl_telefone.setText("Telefone:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_cpf)
                                    .addComponent(lbl_nome)
                                    .addComponent(lbl_telefone))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edt_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                    .addComponent(edt_cpf)
                                    .addComponent(edt_telefone)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(btn_salvar)
                                .addGap(33, 33, 33)
                                .addComponent(btn_cancelar)))
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_warnings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_title)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(edt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_cpf)
                    .addComponent(edt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefone)
                    .addComponent(edt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar)
                    .addComponent(btn_cancelar))
                .addGap(34, 34, 34)
                .addComponent(lbl_warnings)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        String nome = edt_nome.getText().trim();
        String cpf = edt_cpf.getText().trim();
        String telefone = edt_telefone.getText().trim();
        
        if (nome.isEmpty() || cpf.isEmpty() || telefone.isEmpty()) {
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Por favor, preencha todos os campos!");
            return;
        }
        
        Cliente novoCliente = new Cliente();
        novoCliente.setNome(nome);
        novoCliente.setCpf(cpf);
        novoCliente.setTelefone(telefone);
        
        ClienteDAO dao = new ClienteDAO();
        
        if (dao.buscarPorCpf(cpf) != null) {
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Erro: Já existe um cliente cadastrado com este CPF.");
            return;
        }
        
        boolean sucesso = dao.salvar(novoCliente);
        
        if(sucesso){
            lbl_warnings.setForeground(new java.awt.Color(0, 150, 0));
            lbl_warnings.setText("Cliente cadastrado com sucesso!");

            edt_nome.setText("");
            edt_cpf.setText("");
            edt_telefone.setText("");
            edt_nome.requestFocus();
            edt_nome.requestFocus();
        } else {
            lbl_warnings.setForeground(java.awt.Color.RED);
            lbl_warnings.setText("Erro físico ao salvar o cliente no banco de dados.");
        }
        
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JTextField edt_cpf;
    private javax.swing.JTextField edt_nome;
    private javax.swing.JTextField edt_telefone;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_warnings;
    // End of variables declaration//GEN-END:variables
}
