package banco.ui;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form TelaLogin
     */
    private int tentativas = 0;
    private Timer temporizador;
    
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_user = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        edt_user = new javax.swing.JTextField();
        edt_password = new javax.swing.JPasswordField();
        lbl_title = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_user.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        lbl_user.setText("Usuário: ");

        lbl_password.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        lbl_password.setText("Senha: ");

        edt_password.addActionListener(this::edt_passwordActionPerformed);

        lbl_title.setFont(new java.awt.Font("Carlito", 0, 24)); // NOI18N
        lbl_title.setText("Login");
        lbl_title.setMaximumSize(new java.awt.Dimension(43, 19));
        lbl_title.setMinimumSize(new java.awt.Dimension(40, 20));

        btn_login.setText("Entrar");
        btn_login.addActionListener(this::btn_loginActionPerformed);

        lbl_error.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lbl_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_password)
                                .addGap(67, 67, 67)
                                .addComponent(edt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_user)
                                .addGap(54, 54, 54)
                                .addComponent(edt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_login)
                        .addGap(297, 297, 297))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_user))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_password))
                .addGap(39, 39, 39)
                .addComponent(btn_login)
                .addGap(35, 35, 35)
                .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_passwordActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String user = edt_user.getText().trim();
        String password = new String(edt_password.getPassword());
        
        if(user.isEmpty() || password.isEmpty()){
            lbl_error.setForeground(Color.red);
            lbl_error.setText("Por favor, preencha todos os campos!");
            return;
        }
        
        String usuarioCorreto = "miguel";
        String senhaCorreta = "1234";
        int restantes = 3;
        
        if(user.equals(usuarioCorreto) && password.equals(senhaCorreta)){
            new TelaMenuPrincipal().setVisible(true);
            this.dispose();
            
        } else {
            lbl_error.setForeground(Color.red);
            tentativas++;
        
            if(tentativas >= 3){
                btn_login.setEnabled(false);
                
                temporizador = new Timer(1000, new java.awt.event.ActionListener() {
                private int segundosRestantes = 10;

                @Override
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    segundosRestantes--;
                    
                    if (segundosRestantes > 0) {
                        lbl_error.setText("Acesso bloqueado! Aguarde " + segundosRestantes + "s");
                    } else {
                        temporizador.stop();
                        btn_login.setEnabled(true);
                        tentativas = 0;
                        lbl_error.setForeground(new java.awt.Color(0, 150, 0));
                        lbl_error.setText("Sistema liberado. Tente novamente.");
                    }
                }
            });
                temporizador.start();
            } else {
                restantes -= tentativas;
                lbl_error.setText("");
                lbl_error.setText("Usuário e/ou senha incorreto(s). Tentativas restantes: " + restantes);
                edt_password.setText("");
                edt_user.setText("");
                edt_user.requestFocus();
            }
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JPasswordField edt_password;
    private javax.swing.JTextField edt_user;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_user;
    // End of variables declaration//GEN-END:variables
}
